name: ${name}
version: ${version}
description: ${description}
authors: ${authors}
website: ${url}

main: ${mainClass}
api-version: ${apiVersion}
softdepend: [ CoreProtect, ProtocolLib, msCore ]
commands:
  msblock:
    usage: " ꀑ §cИспользуй: /<command> [параметры]"
    permission: msBlock.msblock
    description: Прочья хуйня
permissions:
  msBlock.*:
    default: op
    children:
      msBlock.msblock: true
  msBlock.msblock:
    default: op