name: msBlock
version: ${project.version}
description: A Minecraft plugin with custom blocks for WhoMine
authors: [ MinersStudios, p0loskun ]
website: minersstudios.github.io

main: github.minersStudios.msBlock.Main
api-version: 1.19
database: false
softdepend: [ CoreProtect, ProtocolLib ]
